### PR TITLE
fix transformers 5.x API breaks

### PR DESCRIPTION
**Pull request by niradler**
Three API changes in transformers 5.x break qwen-asr with transformers >=5.0.

**1. check_model_inputs removed**

The decorator @check_model_inputs() was removed in transformers 5.x. The import raises ImportError at module load time, so qwen_asr cannot be imported at all with transformers 5.x.

Fix: guard the import with try/except and fall back to a transparent no-op decorator.

**2. ROPE_INIT_FUNCTIONS default key removed**

The default key was removed from ROPE_INIT_FUNCTIONS in transformers 5.x. Qwen3ASRThinkerTextRotaryEmbedding.__init__ indexes into it with self.rope_type which defaults to default, raising KeyError at model load time.

Fix: fall back to a self-contained RoPE parameter function when the key is missing. Also adds _compute_default_rope_parameters as a method, since the @dynamic_rope_update decorator in transformers 5.x calls it.

**3. pad_token_id missing on Qwen3ASRThinkerConfig**

GenerationMixin in transformers 5.x requires pad_token_id to be explicitly present on the config object. The attribute is not declared as a class-level default on Qwen3ASRThinkerConfig, causing AttributeError during generation.

Fix: declare pad_token_id = None as a class-level default.

### CODE REVIEW

**Comment by ZFTurbo** [comment]
I tried to add these changes. But I still have errors:

`AttributeError: 'Qwen3ASRThinkerTextRotaryEmbedding' object has no attribute 'compute_default_rope_parameters'. Did you mean: '_compute_default_rope_parameters'?`

After renaming _compute_default_rope_parameters to compute_default_rope_parameters and commenting "fix_mistral_regex=True" it started to work on transformers==0.5.3, but results are not the same.

**Comment by ebezzam** [comment]
@niradler there are new checkpoints that have been ported to be Transformers-native with example usage on the model  cards:
- https://huggingface.co/Qwen/Qwen3-ASR-1.7B-hf
- https://huggingface.co/Qwen/Qwen3-ASR-0.6B-hf
- https://huggingface.co/Qwen/Qwen3-ForcedAligner-0.6B-hf
